spring:
    thymeleaf:
        check-template-location: true
        prefix: classpath:/templates/     # view 경로 지정 : src/main/resources/templates
        suffix: .html
        cache: false
    mvc:
        static-path-pattern: /static/**   # 정젹 파일 경로 지정 : src/main/resources/static